accounts:
  - name: alice
    mnemonic: edge victory hurry slight dog exit company bike hill erupt shield aspect turkey retreat stairs summer sadness crush absorb draft viable orphan chuckle exhibit
    coins: ["20000token", "200000000stake", "1000000000uqsr"]
  - name: bob
    mnemonic: harvest ill mean warfare gospel slide tragic palace model excess surprise distance voyage change bus grant special artwork win width group dwarf today jar
    coins: ["10000token", "100000000stake", "1000000000uqsr"]
validator:
  name: alice
  staked: "100000000uqsr"
genesis:
  chain_id: "quasar"
  app_state:
    staking:
      params:
        bond_denom: uqsr
    intergamm:
      params:
        osmo_token_transfer_channels:
          osmosis-test: channel-1
          osmosis: channel-1
        dest_to_intr_zone_map:
          osmosis-01: cosmos
        intr_rcvrs:
          - zone_info:
              chain_id: 'cosmos'
              connection_id: 'connection-02'
            rcvr_address: 'cosmos1ppkxa0hxak05tcqq3338k76xqxy2qse96uelcu'
            next_zone_route_map:
                osmosis-01:
                  local_zone_id: osmosis-01
                  connection_id: 'connection-01'
                  chain_id: "osmosis"
                  transfer_channel_id: "channel-01"
                osmosis-02:
                  local_zone_id: osmosis-02
                  connection_id: 'connection-02'
                  chain_id: "osmosis2"
                  transfer_channel_id: "channel-02"      
    orion:
      params:
        enabled: false
        lp_epoch_id: day #override day for testing
        mgmt_fee_per: '0.003000000000000000'
        perf_fee_per: '0.020000000000000000'
        destination_chain_id: osmosis
        white_listed_pools : [1,2,3]
        osmosis_local_info:
          local_zone_id : osmosis-01
          chain_id: 'osmosis'
          connection_id: 'connection-01'
    qoracle:
      params:
        oracleAccounts: 'quasar1sqlsc5024sszglyh7pswk5hfpc5xtl77gqjwec'
    qbank:
      params:
        enabled: true
        min_orion_epoch_denom_dollar_deposit: '100.000000000000000000'
        orion_epoch_identifier: day #override day for testing
        white_listed_denoms_in_orion:
          - onehop_osmo: ibc/BE1BB42D4BE3C30D50B68D7C41DB4DFCE9678E8EF8C539F6E6A9345048894FCC
            onehop_quasar: ibc/BE1BB42D4BE3C30D50B68D7C41DB4DFCE9678E8EF8C539F6E6A9345048894FCC
            origin_name: uatom
host:
  rpc: ":26659"
  p2p: ":26661"
  prof: ":6061"
  grpc: ":9095"
  grpc-web: ":8091"
  api: ":1311"
  frontend: ":8081"
  dev-ui: ":12351"
client:
  openapi:
    path: "docs/static/openapi.yml"
#  vuex:
#    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake", "10000uqsr"]
