[alias]
wasm = "build --release --target wasm32-unknown-unknown"
unit-test = "test --lib"
schema = "run --bin schema"
test-tube = "test --test test-tube --features test-tube -- --test-threads=1"
test-tube-build = "build --release --lib --target  wasm32-unknown-unknown --target-dir ./test-tube-build"
