[package]
name = "quasar-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quasar-traits = { version = "0.1.0", path = "../quasar-traits"}
cosmos-sdk-proto = { version = "0.14", default-features = false }
prost = { version = "0.11", default-features = false }
thiserror = { version = "1.0.23" }
serde-json-wasm = { version = "0.4.1", default-features = false }
derive_more = { version = "0.99.17", default-features = false, features = ["display"]}
rust_decimal = "1.24.0"
cw20 = "0.13.4"
cosmwasm-std = { version = "1.0.0" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
cosmos-sdk-proto = { version = "0.14.0", default-features = false }
protobuf = { version = "3", features = ["with-bytes"] }
