[alias]
wasm = "build --release --target wasm32-unknown-unknown"
schema = "run --bin schema --features schema"
lint = "clippy -- -D warnings"
lint-fix = "clippy --fix -- -D warnings"
unit-test = "test"
test-vault = "test --lib -p basic-vault"
clip = "clippy -- --D warnings --A deprecated"