name: CL Vault

on:
  pull_request:
    branches:
      - main
    paths:
      - 'smart-contracts/contracts/cl-vault/Cargo.toml'
      - 'smart-contracts/contracts/cl-vault/**.rs'
      - 'smart-contracts/contracts/dex-router-osmosis/Cargo.toml'
      - 'smart-contracts/contracts/dex-router-osmosis/**.rs'
      - '.github/workflows/cl_vault.yml'
      - '.github/workflows/rust_basic.yml'
  push:
    branches:
      - main
    paths:
      - 'smart-contracts/contracts/cl-vault/Cargo.toml'
      - 'smart-contracts/contracts/cl-vault/**.rs'
      - 'smart-contracts/contracts/dex-router-osmosis/Cargo.toml'
      - 'smart-contracts/contracts/dex-router-osmosis/**.rs'
      - '.github/workflows/cl_vault.yml'
      - '.github/workflows/rust_basic.yml'
  workflow_dispatch:

jobs:
  unit-test:
    uses: ./.github/workflows/rust_basic.yml
    with:
      target: 'contracts/cl-vault'
  test-tube:
    uses: ./.github/workflows/rust_test_tube.yml
    with:
      contract: 'cl-vault'
      dex_router_osmosis: true
      prop_test: true
