name: Test Tube

on:
  workflow_call:
    inputs:
      contract:
        required: true
        type: string

jobs:
  test-tube:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Restore dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            ~/go
            **/target
          key: ${{ runner.os }}-cargo-$${{ hashFiles('smart-contracts/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo
      - name: Build test-tube tests
        run: cargo test-tube-build
        working-directory: smart-contracts/contracts/${{ inputs.contract }}
      - name: Run test-tube tests
        run: cargo test-tube
        working-directory: smart-contracts/contracts/${{ inputs.contract }}
